name: MacOS
on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/macos.yml'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/macos.yml'
jobs:
  build-macos:
    runs-on: macos-latest
    env:
      QT_VER: "6.4.0"
      MANUAL_CACHING: "1"
      AUTO_CACHING: "false"
    steps:
      - name: Get repository name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Clone
        uses: actions/checkout@v3
        with:
          submodules: recursive
          path: ${{ env.REPO_NAME }}

      - name: Install dependencies
        run: |
          sudo chown -R `whoami`:admin /usr/local/share

          brew install automake libtool ninja shtool yasm pkg-config

      - name: Set up environment variables
        shell: bash
        run: |
          mkdir Libraries && cd Libraries
          echo "LibrariesPath=`pwd`" >> $GITHUB_ENV

      - name: Generate cache key
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

          xcodebuild -version > CACHE_KEY.txt
          echo $MANUAL_CACHING >> CACHE_KEY.txt
          if [ "$AUTO_CACHING" == "true" ]; then
            thisFile=$REPO_NAME/.github/workflows/macos.yml
            echo `md5 -q $thisFile` >> CACHE_KEY.txt
          fi
          echo "CACHE_KEY=`md5 -q CACHE_KEY.txt`" >> $GITHUB_ENV

      - name: Qt cache
        id: cache-qt
        uses: actions/cache@v3
        with:
          path: ${{ env.LibrariesPath }}/qt-build
          key: ${{ runner.OS }}-qt-${{ env.CACHE_KEY }}

      - name: Qt build
        if: steps.cache-qt.outputs.cache-hit != 'true'
        run: |
          cd $LibrariesPath

          git clone -b v$QT_VER --depth=1 git://code.qt.io/qt/qt5.git qt-sources
          cd qt-sources
          perl init-repository --module-subset=qtbase
          git submodule update qtbase

          ./configure \
          -prefix "$LibrariesPath/qt-build" \
          -release \
          -opensource \
          -confirm-license \
          -static \
          -opengl desktop \
          -no-openssl \
          -nomake examples \
          -nomake tests \
          -optimize-size \
          -platform macx-clang

          cmake --build . --parallel $NUMBER_OF_PROCESSORS
          cmake --install .

