name: Windows

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/win.yml'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/win.yml'
jobs:
  build-windows:
    runs-on: windows-latest
    env:
      VC: "call vcvars32.bat && cd Libraries"
      QT_VER: "6.4.0"
      MANUAL_CACHING: "2"
      AUTO_CACHING: "false"
    steps:
      - name: Get repository name
        shell: bash
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Clone
        uses: actions/checkout@v3
        with:
          path: ${{ env.REPO_NAME }}

      - name: Set up environment variables
        shell: bash
        run: |
          echo "C:\\Strawberry\\perl\\bin\\" >> $GITHUB_PATH
          echo "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\" >> $GITHUB_PATH
          mkdir Libraries && cd Libraries
          echo "Convert unix path to win path"
          p=`pwd | sed 's#^/[d]#d:#g' |sed 's#/#\\\\#g'`
          echo "LibrariesPath=$p" >> $GITHUB_ENV

      - name: Save msbuild version
        shell: cmd
        run: |
          call vcvars32.bat
          msbuild -version > CACHE_KEY.txt

      - name: Generate cache key
        shell: bash
        run: |
          echo $MANUAL_CACHING >> CACHE_KEY.txt
          if [ "$AUTO_CACHING" == "true" ]; then
            thisFile=$REPO_NAME/.github/workflows/win.yml
            echo `md5sum $thisFile | awk '{ print $1 }'` >> CACHE_KEY.txt
          fi
          echo "CACHE_KEY=`md5sum CACHE_KEY.txt | awk '{ print $1 }'`" >> $GITHUB_ENV

      - name: Qt cache
        id: cache-qt
        uses: actions/cache@v3
        with:
          path: ${{ env.LibrariesPath }}/qt-build
          key: ${{ runner.OS }}-qt-${{ env.CACHE_KEY }}

      - name: Qt configure
        if: steps.cache-qt.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          %VC%
          git clone -b v%QT_VER% --depth=1 git://code.qt.io/qt/qt5.git qt-sources
          cd qt-sources
          perl init-repository --module-subset=qtbase
          git submodule update qtbase
          configure ^
          -prefix "%LibrariesPath%\qt-build" ^
          -release ^
          -opensource ^
          -confirm-license ^
          -static ^
          -static-runtime ^
          -no-opengl ^
          -mp ^
          -skip webengine ^
          -nomake tools ^
          -nomake examples ^
          -nomake tests ^
          -optimize-size ^
          -platform win32-msvc

      - name: Qt build
        if: steps.cache-qt.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          %VC%
          cd qt-sources
          cmake --build . --parallel %NUMBER_OF_PROCESSORS%
          cmake --install .

      - name: OpenAL Soft cache
        id: cache-openal
        uses: actions/cache@v3
        with:
          path: ${{ env.REPO_NAME }}/submodules/openal-soft
          key: ${{ runner.OS }}-openal-${{ env.CACHE_KEY }}
      - name: OpenAL Soft build
        if: steps.cache-openal.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          cd %REPO_NAME%
          git submodule update --init submodules/openal-soft
          cd submodules/openal-soft/build
          %VC%
          cmake .. -A Win32 -D LIBTYPE:STRING=STATIC -D FORCE_STATIC_VCRT=ON -D ALSOFT_BACKEND_WASAPI=OFF
          msbuild -m OpenAL.vcxproj /property:Configuration=Release
          
      - name: FFmpeg cache
        id: cache-ffmpeg
        uses: actions/cache@v3
        with:
          path: ${{ env.REPO_NAME }}/submodules/FFmpeg
          key: ${{ runner.OS }}-FFmpeg-${{ env.CACHE_KEY }}-${{ hashFiles('soundbox/submodules/scripts/build_ffmpeg_win.sh') }}
      - name: FFmpeg build
        if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          choco install --no-progress -y msys2 yasm
          cd %REPO_NAME%
          git submodule update --init submodules/FFmpeg
          cd submodules/FFmpeg
          %VC%
          set CHERE_INVOKING=enabled_from_arguments
          set MSYS2_PATH_TYPE=inherit
          dir
          call c:\tools\msys64\usr\bin\bash --login ../scripts/build_ffmpeg_win.sh

      - name: SoundBox build
        shell: cmd
        run: |
          cd %REPO_NAME%
          cmake -A Win32 -DCMAKE_PREFIX_PATH=%LibrariesPath%\qt-build
          call vcvars32.bat
          msbuild -m soundbox.sln /nologo /p:Configuration=Release,Platform=Win32

      - uses: actions/upload-artifact@v3
        name: Upload artifact
        with:
          name: soundbox-windows
          path: ${{ env.REPO_NAME }}\Release\soundbox.exe
